# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Ultimate Evolution
tagline:          'Ultimate frisbee club in Adelaide'
description:      'An ultimate frisbee club of men and women in Adelaide, Australia'
url:              http://ultimateEvolution.github.io

author:
  name:           'Drew Hendrickson'
  url:            https://twitter.com/athendri

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/ultimateEvolution/ultimateEvolution.github.io